### ISSUE TITLE
I want to build a registration system... can you link me to a tut?

### ISSUE THREAD

**Issue by GoOpaque** [KingPixil/ama#10]
I'd like to use JS

**Comment by kbrsh** [comment]
You would need to use Node.js, there are many modules for registration. One is Passport. 

Here are a couple tutorials:
- http://code.tutsplus.com/tutorials/authenticating-nodejs-applications-with-passport--cms-21619
- http://www.jokecamp.com/tutorial-passportjs-authentication-in-nodejs/
- https://blog.risingstack.com/node-hero-node-js-authentication-passport-js/

Let me know if this is what you wanted, thanks for asking @GoOpaque :+1:
