### ISSUE TITLE
Regarding your logo 

### ISSUE THREAD

**Issue by leovarmak** [KingPixil/ama#18]
I am in love with your logo. But I feel that is way too similar to the Marshmallow logo. Whats your take on this ? Like are your kinda of inspired from it ?

**Comment by kbrsh** [comment]
@leovarmak Awesome! I'm glad you like my logo :smile:, I had no idea there was a logo like that for Marshmallow. I wasn't really inspired really, I just took a letter K, and filled it in, and added some nice gradients. I didn't really know a logo like that existed, really. 

The marshmallow logo is different though, it is one color, and an M shape. My logo is two colors for two triangles, and has a gradient background.

Hope this helps, @leovarmak
Thanks for asking :+1:
