### ISSUE TITLE
Why did you make Wing? 

### ISSUE THREAD

**Issue by dalanmiller** [KingPixil/ama#19]
It has a very skeleton.css vibe with the basic features from Bootstrap. Why did you feel like you wanted to make something new?

**Comment by kbrsh** [comment]
Hey @dalanmiller 

Skeleton is not updated (last commit in 2014), and didn't really provide everything I looked for in a css framework, it is a little **too** light. Wing is updated very often, and has some more features, all packed in a _very_ lightweight file size, at around 4.6 kb, compared to Bootstrap's **88kb**. Hope this answers your question.

Thanks for asking @dalanmiller :+1:
