### ISSUE TITLE
When did you start programming? How long did it take you to get this good? What programming languages do you currently know?

### ISSUE THREAD

**Issue by ColinSeguin** [KingPixil/ama#23]
Obviously you know HTML, CSS, Javascript, and the Node.JS library, but do you know any others? Your work is super impressive, especially since you are 13 years old.  I'm currently 13 years old and I literally just started learning HTML and CSS today. Also am learning C because I want to especially work with learning about computers and do low-level stuff. Also know Java and I am going to make games using it for desktop and mobile soon.

**Comment by kbrsh** [comment]
Hey @ColinSeguin!

I started programming about 2 years ago, with my first HTML "Hello World!" page. I got the interest one day by just browsing the web and wondering how the website actually worked under the hood. I searched up "How to make a website" and it began from there. Only recently did I start really getting into making things. 

I haven't found this method online, but to learn the basics of programming, I would think of a project. For example, a URL shortener. After that, I use my current knowledge to get started, and when I don't know something, I look in a documentation or just search it up. It's a super satisfying way of learning, as you have a completed product in the end.

I currently have knowledge in:
- HTML
- CSS
- Javascript
- Node.js
- Ruby
- Python
- Go

After you get the basics of a language, and learn one really nicely, other ones will be easy. You are just learning the new syntax and the quirks of the language. With this, you can easily adapt to any language.

Feel free to reach out to me anytime if you need any help, let me know what you've built!
Congrats on getting started! Thanks for asking! 😄 👊 👍

**Comment by ColinSeguin** [comment]
Cool! I'd love to stay in touch. I don't know what my first website will be but probably my portfolio/blog site. Btw, totally irrelevant but I saw in a Reddit post (basically how I found you), you said you are from Sunny California. Turns out I am too. Coincidence lol

**Comment by kbrsh** [comment]
Wow! Super cool you came from Reddit, cool to see you are in California 🌞  too!
