### ISSUE TITLE
What project are you most proud of? And why?

### ISSUE THREAD

**Issue by goknsh** [KingPixil/ama#8]

**Comment by kbrsh** [comment]
I can't say that I have a favorite, but if I had to pick, it would probably be my 180 Websites in 180 Days Project. I learned my base knowledge from doing that. My favorite framework I made is probably Wing, or Paint. Wing is a CSS Framework that started to get a little popular recently, check it out [here](https://github.com/KingPixil/wing). It is very minimal and took me some time to get it done. [Paint](https://github.com/KingPixil/paint) is a JQuery clone I spent a ton of time optimizing. One of my most popular projects is [Colicious](http://colicious.ga), after being #1 on Product Hunt! That is something I am definitely proud of. Sorry if this is like a list of projects, but I like all of them, after all, in each project I make, I learn something new, and have something out there! :+1:
